on:
  push:
    branches:
      - fb-ci
      - fb-indent-v3

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Publish
      run: |
            npm install
            npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}