on:
  push:
    branches:
      - fb-ci
      - fb-indent-v3
  release:
    types:
    - created  
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: fb-indent-v3
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - name: Publish
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}